spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.101.104:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
